  # DO NOT CALL DIRECTLY - use include-task to consume this module

  - name: Make sure simpleui-git distributions is UP-TO-DATE.
    local_action: command bash "{{ simpleui_root }}/deploy/is_dist_stale.bash"
    connection: local
    become: true
#    ignore_errors: yes

  - name: "password test {{ ansible_become_password }}"
    local_action: command echo "test"
    connection: local
    register: echo_test_out
    become: true
  - debug: msg="{{ echo_test_out }}"

  - name: "Remove Web Staging Folder {{ local_stage_dir }} web"
    local_action: file path="{{ local_stage_dir }}" state=absent
    connection: local
    become: true

  - name: "Create Web Staging Folder {{ local_stage_dir }}/web/{{ web_app_name }}"
    local_action: file path="{{ local_stage_dir }}/web/{{ web_app_name }}" state=directory mode=0755 owner=service group=service
    connection: local
    become: true

  - name: "Merge ng-simpleui into derived app {{ web_app_name }}"
    local_action: command "{{ simpleui_root }}/deploy/merge-derived-app.sh" "{{ simpleui_root }}" "{{ simpleui_derivative_folder }}"  "{{ local_stage_dir }}/web/{{ web_app_name }}" -d {{ include_mock_data }} -p "{{ nodejs_port }}"
    connection: local
    become: true
    register: merge_script_out

  - debug: msg="{{ merge_script_out }}"

  #- name: 'Create local web packaging application'
  #  local_action: script create-bms-web-setup-bundle.sh {{ local_stage_dir }} quiet

  - name: "Integrate the parameters app if requested ( copy_params_app : {{ copy_params_app }} )"
    include_tasks:
        file: integrate_params_app.yml
    when: copy_params_app is defined and copy_params_app

  - name: "Set custom web-app list for service (if required)"
    local_action: replace path="{{ local_stage_dir }}/web/{{ web_app_name }}/simpleui-server/{{ web_app_name }}-web.service" regexp='--appName={{ web_app_name }}' replace="--appName={{ web_service_apps_list }}"
    connection: local
    become: true
    when: web_service_apps_list is defined and web_service_apps_list

  # If NOT using a simpleui-server, remove the folder
  - name: "Remove {{ local_stage_dir }}/web/{{ web_app_name }}/simpleui-server/node_modules folder if web_service_apps_list is undefined or false"
    local_action: file path="{{ local_stage_dir }}/web/{{ web_app_name }}/simpleui-server/node_modules" state=absent
    connection: local
    become: true
    when: (web_service_apps_list is undefined) or (not web_service_apps_list)

  - name: "Create the local bundle file {{ web_bundle_file }}"
    local_action: archive path="{{ local_stage_dir }}" dest="/tmp/{{ web_bundle_file }}"
    connection: local

    # -
    # END SECTION - CREATE_LOCAL_ARCHIVE
