# DO NOT CALL DIRECTLY - use include-task to consume this module

#+ Start install legacy module-derivative-app (functionality from Purification/setup/ - create-web-setup-OBSOLETE.sh and web-setup-OBSOLETE.sh)

- name: "Create local legacy library archive '/tmp/{{ legacy_module_derivative_web_app_bundle }}' if it does not already exist."
  connection: local
  local_action:
    module: archive
    path:
      - "{{ common_web_src }}/../module_derivative/web/appJs"
      - "{{ common_web_src }}/../module_derivative/web/config.js"
      - "{{ common_web_src }}/../module_derivative/web/css"
      - "{{ common_web_src }}/../module_derivative/web/favicon.ico"
      - "{{ common_web_src }}/../module_derivative/web/images"
      - "{{ common_web_src }}/../module_derivative/web/io.html"
      - "{{ common_web_src }}/../module_derivative/web/js"
      - "{{ common_web_src }}/../module_derivative/web/php/"
      - "{{ common_web_src }}/../module_derivative/web/ppcJs"
      - "{{ common_web_src }}/../module_derivative/web/pumps.html"
    dest: "/tmp/{{ legacy_module_derivative_web_app_bundle }}"
    format: "gz"

- name: "Create local legacy library archive '/tmp/fleetviewer_bundle.tgz' if it does not already exist."
  connection: local
  local_action:
    module: archive
    path:
      - "{{ common_web_src }}/../module_derivative/web/fleetviewer"
    dest: "/tmp/fleetviewer_bundle.tgz"
    format: "gz"

- name: "Extract the files from the legacy library archive '{{ common_web_src }}/dojo-release-1.9.0.tar.gz' to /var/www/{{ web_app_name }}/dojo-release-1.9.0"
  unarchive:
    src:  "{{ common_web_src }}/dojo-release-1.9.0.tar.gz"
    dest: "/var/www/{{ web_app_name }}/"
    owner: "{{ remote_web_user }}"
    group: "{{ remote_web_group }}"
  become: true

- name: "Create a symbolic link from '/var/www/{{ web_app_name }}/dojo-release-1.9.0' to '/var/www/{{ web_app_name }}/dojo-toolkit' if it doesn't exist"
  file:
    src: "/var/www/{{ web_app_name }}/dojo-release-1.9.0"
    dest: /var/www/{{ web_app_name }}/dojo-toolkit
    owner: "{{ remote_web_user }}"
    group: "{{ remote_web_group }}"
    state: link
  become: true

- name: "Create a symbolic link from '/var/www/{{ web_app_name }}/dojo-release-1.9.0' to '/var/www/dojo-toolkit' if it doesn't exist"
  file:
    src: "/var/www/{{ web_app_name }}/dojo-release-1.9.0"
    dest: /var/www/dojo-toolkit
    owner: "{{ remote_web_user }}"
    group: "{{ remote_web_group }}"
    state: link
  become: true

- name: "Create a symbolic link from '/var/www/{{ web_app_name }}/php' to '/var/www/php' if it doesn't exist"
  file:
    src: "/var/www/{{ web_app_name }}/php"
    dest: /var/www/php
    owner: "{{ remote_web_user }}"
    group: "{{ remote_web_group }}"
    state: link
  become: true

- name: "Extract the files from the legacy library archive '/tmp/{{ legacy_module_derivative_web_app_bundle }}' to /var/www/{{ web_app_name }}"
  unarchive:
    src: "/tmp/{{ legacy_module_derivative_web_app_bundle }}"
    dest: "/var/www/{{ web_app_name }}/"
    owner: "{{ remote_web_user }}"
    group: "{{ remote_web_group }}"
  become: true

- name: "Create a symbolic link from '/var/www/{{ web_app_name }}/ppcJs' to '/var/www/ppcJs' if it doesn't exist"
  file:
    src: "/var/www/{{ web_app_name }}/ppcJs"
    dest: /var/www/ppcJs
    owner: "{{ remote_web_user }}"
    group: "{{ remote_web_group }}"
    state: link
  become: true

#- name: "Create a symbolic link from '/var/www/{{ web_app_name }}/php' to '/var/www/php' if it doesn't exist"
#  file:
#    src: "/var/www/{{ web_app_name }}/php"
#    dest: /var/www/php
#    owner: "{{ remote_web_user }}"
#    group: "{{ remote_web_group }}"
#    state: link
#  become: true


- name: "Copy legacy module derivative app file 'io.html' to '/var/www/{{ web_app_name }}/'"
  copy:
    src:  "{{ common_web_src }}/../module_derivative/web/io.html"
    dest: "/var/www/{{ web_app_name }}/"
    group: "{{ remote_web_group }}"
    owner: "{{ remote_web_user }}"
  become: true
#
#- name: "Copy legacy module derivative app file 'pumps.html' to '/var/www/{{ web_app_name }}/'"
#  copy:
#    src: "{{ common_web_src }}/../module_derivative/web/pumps.html"
#    dest: "/var/www/{{ web_app_name }}/"
#    group: "{{ remote_web_group }}"
#    owner: "{{ remote_web_user }}"
#  become: true
#

- name: "Create folder /var/log/ppcData if it doesn't exist"
  file:
    path: "/var/log/ppcData"
    owner: "{{ remote_web_user }}"
    group: "{{ remote_web_group }}"
    state: directory
    mode: '0777'
  become: true

- name: "Create file /var/log/bsc-command.log if it doesn't exist"
  file:
    path: "/var/log/bsc-command.log"
    owner: "{{ remote_web_user }}"
    group: "{{ remote_web_group }}"
    state: touch
    mode: '0777'
  become: true

- name: "Create file /var/log/sui-data.log if it doesn't exist"
  file:
    path: "/var/log/sui-data.log"
    owner: "{{ remote_web_user }}"
    group: "{{ remote_web_group }}"
    state: touch
    mode: '0777'
  become: true

- name: "Create a symbolic link from '/var/www/$module/php/{{ web_app_name }}/php/sLogger.php' to '/var/www/{{ web_app_name }}/php/modules/sLogger.php' if it doesn't exist"
  file:
    src:  "/var/www/{{ web_app_name }}/php/sLogger.php"
    dest: "/var/www/{{ web_app_name }}/php/modules/sLogger.php"
    owner: "{{ remote_web_user }}"
    group: "{{ remote_web_group }}"
    state: link
  become: true

- name: "Extract the files from the legacy library archive '/tmp/fleetviewer_bundle.tgz' to /var/www/"
  unarchive:
    src: "/tmp/fleetviewer_bundle.tgz"
    dest: "/var/www/"
    owner: service
    group: service
  become: true

- name: "Extract the files from the legacy library archive '/tmp/fleetviewer_bundle.tgz' to /var/www/"
  unarchive:
    src: "/tmp/fleetviewer_bundle.tgz"
    dest: "/var/www/"
    owner: service
    group: service
  become: true
