# Notes:
#   1. Does not use Parameters, and hence has the variable
#      copy_params_app: false
---
- hosts: all
  vars:
    app_config_props_file: MockServer.bms.properties
    copy_params_app: false
    simpleui_derivative_folder: ../web/simple_ui.derivative/
    nodejs_port: 2079
    web_app_name: simpleui
    web_service_apps_list: "{{ web_app_name }}"
    #The following are from var/common-vars.yml in other deploy directories
    archive_dir: /vionx
    unique_suffix: "{{ ansible_facts['date_time']['date'] }}-{{ ansible_facts['date_time']['hour'] }}-{{ ansible_facts['date_time']['minute'] }}--{{ ansible_facts['date_time']['second'] }}"
    common_web_src: /home/jscarsdale/vionx_linux/target/common/web

  remote_user: "{{ lookup('env', 'REMOTE_WEB_USER') }}"
  tasks:
    - include_vars:
        file: "{{ simpleui_root }}/deploy/common-vars.yml"

    - include_tasks:
        file: "{{ simpleui_root }}/deploy/build-derived-app-bundle.yml"

    - include_tasks:
        file: "{{ simpleui_root }}/deploy/install-derived-app-bundle.yml"
