---
- hosts: all
  vars:
    nodejs_version: 16
    nodejs_bundle: "setup_{{ nodejs_version }}.x"

  remote_user: service

  tasks:
    - name: "Remove existing nodejs"
      command: "apt -y remove nodejs"
      become: true

    - name: "Download nodejs bundle"
      get_url:
        url: "https://deb.nodesource.com/{{ nodejs_bundle }}"
        dest: "/tmp/{{ nodejs_bundle }}"

    - name: "Execute nodejs bundle"
      command: "bash {{ nodejs_bundle }}"
      args:
        chdir: "/tmp"
      become: true

    - name: "Install nodejs"
      command: "apt -y install nodejs"
      become: true