FROM node:16-bullseye
RUN mkdir /usr/src/app
RUN mkdir /usr/src/app/base_app
RUN mkdir /usr/src/app/simpleui-server

WORKDIR /usr/src/app/base_app
RUN npm install -g @angular/cli

WORKDIR /usr/src/app/simpleui-server
RUN npm install -g @angular/cli


