version: '3.5'
services:
  frontend-angular-service:
    image: angular-dev-image
    container_name: simpleui_dev_container
    build: .
    working_dir: /usr/src/app/
    volumes:
      - '../base_app:/usr/src/app/base_app'
      - '../base_app/dist:/var/www/simpleui'
      - '../simpleui-server:/usr/src/app/simpleui-server'
      - '../simpleui-server/test/config:/opt/config'
      - '../simpleui-server/test/data/bms:/var/www/bms'
      - '../simpleui-server/test/data/dcbatt-data:/var/www/dcbatt-data'
      - '.:/usr/src/app/develop_docker'
      - '/tmp/apache2:/var/volatile/tmp/apache2'
    ports:
      - '4100:4100'
      - '4200:4200'
      - '9229:9229'
    command:
      /bin/bash /usr/src/app/develop_docker/install-prereqs-and-start-server.bash
