---
# use flag --extra-vars "remupdate=true" to complete the distribution to all VECs.
# Without the flag set the packages are created and copied to the BMS server staging area only.
- hosts: all
  vars:
    app_name: acinverter
    ac_inv_app_binary: ACInverter
    ac_inv_app_source_dir: "{{ lookup('env','DIR_X86_BIN') }}/{{ ac_inv_app_binary }}/bin"
  remote_user: service
  tasks:
  - include_vars:
      file: commonvars.yml
  - name: Prep Local Staging Area
    local_action: file path={{ unit_config_source_dir }} state=absent
  - local_action: file path={{ unit_config_source_dir }} state=directory mode=0755
  - name: Prep Target Staging Area
    file:
      path: "{{ bms_stage_dir }}"
      state: directory
      mode: 0777

  - name: Copy Binary To Local Stage Area
    copy: src={{ ac_inv_app_source_dir }}/{{ ac_inv_app_binary }} dest={{ bms_stage_dir }}/{{ ac_inv_app_binary }}

  - name: Backup Existing Binary
    stat: path="/opt/bin/{{ ac_inv_app_binary }}"
    register: result
  - copy: remote_src=yes src=/opt/bin/{{ ac_inv_app_binary }} dest={{ archive_dir }}/{{ ac_inv_app_binary }}{{ archive_suffix }}
    when: result.stat.exists

  - name: Stop application service
    service:
      name: acinv
      state: stopped
    become: true

  - name: Deploy binary
    command: install -D {{ bms_stage_dir }}/{{ ac_inv_app_binary }} /opt/bin/{{ ac_inv_app_binary }}

  - name: Get binary md5
    command: md5sum /opt/bin/{{ ac_inv_app_binary }}
    register: md5output
  - debug: msg="{{ md5output.stdout }}"
  - name: Set executable permissions
    file:
      path: /opt/bin/{{ ac_inv_app_binary }}
      state: file
      mode: 0777

  - name: Start application service
    service:
      name: acinv
      state: started
    become: true

  - pause:
      seconds: 20
    # Make sure the bms service app has started
  - name: Confirm EMS is running
    command: systemctl is-active acinv
    register: agent_status
    failed_when: "'failed' in agent_status.stdout"
    changed_when: False

