---
- hosts: all
  vars:
    local_stage_dir: /tmp/proxy-staging-local
    remote_stage_dir: /tmp/proxy-staging-remote
    bundle_file: proxy-web-setup-bundle.tgz
    web_deploy_dir: /var/www/device
  remote_user: service
  tasks:
    - name: Mount c1-smu
      mount:
        path: "{{ web_deploy_dir }}/c1-smu-dat"
        src: //c1-smu/sys_data
        fstype: cifs
        opts: user=service,password=,iocharset=utf8
        state: mounted
      become: true

    - name: Mount c1-vcu
      mount:
        path: "{{ web_deploy_dir }}/c1-vcu-dat"
        src: //c1-vcu/sys_data
        fstype: cifs
        opts: user=service,password=,iocharset=utf8
        state: mounted
      become: true

    - name: Mount c1-scu-a1
      mount:
        path: "{{ web_deploy_dir }}/c1-scu-a1-dat"
        src: //c1-scu-a1/sys_data
        fstype: cifs
        opts: user=service,password=,iocharset=utf8
        state: mounted
      become: true

    - name: Mount c1-scu-a2
      mount:
        path: "{{ web_deploy_dir }}/c1-scu-a2-dat"
        src: //c1-scu-a2/sys_data
        fstype: cifs
        opts: user=service,password=,iocharset=utf8
        state: mounted
      become: true

    - name: Mount c1-scu-b1
      mount:
        path: "{{ web_deploy_dir }}/c1-scu-b1-dat"
        src: //c1-scu-b1/sys_data
        fstype: cifs
        opts: user=service,password=,iocharset=utf8
        state: mounted
      become: true

    - name: Mount c1-scu-b2
      mount:
        path: "{{ web_deploy_dir }}/c1-scu-b2-dat"
        src: //c1-scu-b2/sys_data
        fstype: cifs
        opts: user=service,password=,iocharset=utf8
        state: mounted
      become: true

    - name: 'Restart apache2'
      service:
        name: apache2
        state: restarted
      become: true
    # Cleanup, remove remote staging directory and files
    - name: 'Remove remote staging area folder'
      file:
        path: "{{ remote_stage_dir }}"
        state: absent
      become: true
    - name: 'Remove tar file'
      file:
        path: /tmp/{{ bundle_file }}
        state: absent
      become: true
