name: Sui CI Frontend Tests

on: [push]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./base_app
    steps:
			- uses: actions/checkout@v2		# checkout sui repo
			- uses: actions/setup-node@v2	# use nodejs v18
				with:
				node-version: '18'
			- name: Run Karama Tests
				run: |
				npm install
				npm run ci:test
